# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6hXUGoI-h5hSR8aV8tFaqmaAAEE2K8B
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import joblib
import io
import numpy as np

# ------------------------------------------------------------
# Load Dataset
# ------------------------------------------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("employee_profiles_synthetic.csv")

    float_cols = df.select_dtypes(include=["float64"]).columns
    df[float_cols] = df[float_cols].round(2)

    categorical_cols = ["Department", "Gender", "PromotionReady", "WillImprove", "Attrition"]
    for col in categorical_cols:
        if col in df.columns:
            df[col] = df[col].astype("category")

    return df

df = load_data()

st.set_page_config(page_title="HR Predictive Analytics Dashboard", layout="wide")
st.title("🔮 HR Predictive Analytics Dashboard with Model Upload")

# Initialize model and model_features for scope and control flow
model = None
model_features = []
model_loaded_successfully = False

# ------------------------------------------------------------
# Upload model
# ------------------------------------------------------------
st.sidebar.header("📌 Upload Trained .pkl Model for Prediction")
model_file = st.sidebar.file_uploader("Upload .pkl file", type=["pkl"])

if model_file is None:
    st.warning("⚠ Upload your trained .pkl model to start predictions.")
    st.dataframe(df)
    st.info("No model file uploaded. Displaying raw data only.")
    # Removed st.stop() as it causes unexpected behavior in Colab's direct execution.
else:
    # ------------------------------------------------------------
    # Load Model
    # ------------------------------------------------------------
    try:
        model = joblib.load(io.BytesIO(model_file.read()))
        st.success("✅ Model loaded successfully!")
        model_loaded_successfully = True
    except Exception as e:
        st.error(f"❌ Error loading model: {e}")
        st.info("Model could not be loaded. Displaying raw data only.")
        model_loaded_successfully = False

    # ------------------------------------------------------------
    # Align dataset columns to model feature order
    # ------------------------------------------------------------
    if model_loaded_successfully: # Only proceed if model was loaded
        try:
            model_features = list(model.feature_names_in_)  # works for scikit models
        except Exception:
            st.error("❌ Model does not store feature names. Cannot match dataset.")
            st.info("Model features could not be extracted. Displaying raw data only.")
            model_loaded_successfully = False

# Now, execute prediction and visualization parts only if model was loaded successfully
if model_loaded_successfully:
    # Add missing engineered columns to df
    for col in model_features:
        if col not in df.columns:
            df[col] = 0  # default fallback value

    # Align dataset to model expected order
    df_aligned = df[model_features]

    # ------------------------------------------------------------
    # Generate Predictions
    # ------------------------------------------------------------
    try:
        df["PredictedAttritionProb"] = model.predict_proba(df_aligned)[:, 1]
        df["PredictedAttrition"] = (df["PredictedAttritionProb"] > 0.50).astype(int)
    except Exception as e:
        st.error(f"❌ Prediction error: {e}")
        st.info("Prediction failed. Displaying raw data only.")
        model_loaded_successfully = False # Set to false if prediction fails

if model_loaded_successfully: # Wrap KPI cards and visuals as well
    st.write(f"### Total Employees: {len(df)}")

    # ------------------------------------------------------------
    # KPI Cards
    # ------------------------------------------------------------
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Actual Attrition %", f"{df['Attrition'].mean()*100:.2f}%")
    col2.metric("Predicted Attrition %", f"{df['PredictedAttrition'].mean()*100:.2f}%")
    col3.metric("Avg Predicted Probability", f"{df['PredictedAttritionProb'].mean():.2f}")
    col4.metric("High-Risk Employees (Prob > 0.75)", sum(df['PredictedAttritionProb'] > 0.75))

    # ------------------------------------------------------------
    # 🔥 6 Visuals
    # ------------------------------------------------------------

    # 1 — Employee Count by Department
    st.subheader("📊 Visual 1 — Employee Count by Department")
    st.plotly_chart(px.bar(df, x="Department", title="Employee Count by Department"), width='stretch')

    # 2 — Gender Distribution by Department
    st.subheader("📊 Visual 2 — Gender Distribution by Department")
    st.plotly_chart(px.histogram(df, x="Department", color="Gender",
                                 barmode="group", title="Gender Breakdown per Department"),
                    width='stretch')

    # 3 — Actual Attrition by Department
    st.subheader("📊 Visual 3 — Actual Attrition by Department")
    st.plotly_chart(px.histogram(df, x="Department", color="Attrition",
                                 barmode="group", title="Actual Attrition by Department"),
                    width='stretch')

    # 4 — Predicted Attrition by Department
    st.subheader("📊 Visual 4 — Predicted Attrition by Department")
    st.plotly_chart(px.histogram(df, x="Department", color="PredictedAttrition",
                                 barmode="group", title="Predicted Attrition Risk by Department"),
                    width='stretch')

    # 5 — Satisfaction × Stress Probability Heatmap
    st.subheader("📊 Visual 5 — Heatmap of Predicted Attrition Probability")
    st.plotly_chart(px.density_heatmap(df, x="Satisfaction", y="Stress", z="PredictedAttritionProb",
                                       title="Probability Density Map (Higher = Higher Risk)"),
                    width='stretch')

    # 6 — Actual vs Predicted Attrition % by Department
    st.subheader("📊 Visual 6 — Actual vs Predicted Attrition % by Department")
    df_compare = df.groupby("Department")[["Attrition", "PredictedAttrition"]].mean().reset_index()
    df_compare["Attrition"] *= 100
    df_compare["PredictedAttrition"] *= 100
    st.plotly_chart(px.bar(df_compare, x="Department", y=["Attrition", "PredictedAttrition"],
                           barmode="group", title="Actual vs Predicted Attrition % Comparison"),
                    width='stretch')

# ------------------------------------------------------------
# Table + Download
# ------------------------------------------------------------
st.subheader("📋 Employee Dataset with Predictions Added")
st.dataframe(df, width='stretch')

csv = df.to_csv(index=False).encode("utf-8")
st.download_button("⬇ Download Enhanced Dataset with Predictions",
                   data=csv,
                   file_name="employee_predictions.csv",
                   mime="text/csv")

